### ISSUE TITLE
Enhance Wizard implementation

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#1007]
Starting a list of behaviors/enhancements for wizard page:
- [x] Demonstrate validation per step
- [x] Scroll to top of step when someone advances
- [x] Discuss sticky wizard footer display on large screens (button feels very far from content)

**Comment by gregfuruiye** [comment]
I think we only need to show what happens when the user clicks 'cancel'. What happens when they confirm cancel is up to the service team. It could vary depending on how they entered the wizard to begin with. However, if we wanted to demonstrate something, we could create a kind of dummy launch page that would allow them to start the wizard again.

click cancel --> cancel layer --> click to confirm cancel --> close the layer and the wizard and show some simple homepage with sidebar and header and one big card/button in main --> click the card/button 'Start Wizard'

**Comment by taysea** [comment]
Gotcha, it feels like for simplicity of the code/purpose of keeping it focused on wizard then we should stop at the `cancel` layer. otherwise, lots of additional code will be living in the "show code" section of the site which may clutter the readability of the example.
