### ISSUE TITLE
Publish first pass at Table

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#1014]
### Deliverables

- publish content in the Table page of the design system
- at least one example
- initial guidance

### Aspects

Add starter content for aspects included in the initial designs. These can be rough first cuts but should at least hint at these being areas we will have more to say on.

- cell alignment
- cell truncation vs. wrapping
- sort
- search
- selection
- interaction via entire row vs. individual cells, mouse and keyboard
- pagination vs. infinite scroll

Note, filtering will be covered in a separate issue.

**Comment by halocline** [comment]
To Dos:
- Add Icon for sorting on column headers (solid caret/chevron up/down)
- Column Header Buttons
  - Need background on hover --> Behave as `plain` today, may be okay, but design calls for behavior like `default`
  - fill is set to "vertical", does not allow for "horizontal", true, etc. https://github.com/grommet/grommet/blob/d1d440ffbf7f0db50213b15585b29aca5f6e447d/src/js/components/DataTable/Header.js#L72

**Comment by halocline** [comment]
[From Slack](https://hpe.slack.com/archives/GPPLUK6LR/p1599171792004400?thread_ts=1599059119.000900&cid=GPPLUK6LR)
A few thoughts …

- [ ] accessible rows, I think the first cell in each row should typically have unique content, with scope="row" , and with a different style to indicate it is an identifier.
- [ ] agreed with Greg’s comment about deciding whether to put units in the header or body cells, I can see arguments for each, might be a good quick-research topic
- [ ] I think the Sorting example should start with one of the columns sorted, otherwise I look at it and am struggling to locate the visual that matches the mention of the “caret” indicator
- [ ] I think the use of Button within the table header cells should probably be plain and controlled by the table.
- [ ] “Selecting multiple records & batch actions” would benefit from a summary label confirming how many are selected.
- [ ] I think we should encourage using a heading for the table to succinctly communicate its contents, and should do that in our examples
- [ ] I think we should also include Filtering in Related
- [ ] One other aspect we should cover is responsiveness, and some guidance on deciding how to organize and include or exclude columns.
