### ISSUE TITLE
Table cell content scaling

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#1081]
Provide guidance on when to:
- wrap content
- truncate content, and show a variety of truncation options
- rely on horizontal scroll

**Comment by vavalos5** [comment]
@halocline what do you mean by "rely on horizontal scroll?"

**Comment by vavalos5** [comment]
Including Figma file for reference: https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=1473%3A0

**Comment by halocline** [comment]
> @halocline what do you mean by "rely on horizontal scroll?"

Could've been worded better. Is scrolling within a table cell a pattern we recommend / discourage?

For all of these the intent is "what do we do when content is too large for the cell size? how do we visually treat this? how are users able to view the entirety of the cell's content? or do they? perhaps they have to export the data?"

**Comment by ericsoderberghp** [comment]
I don't think we should recommend scrolling within a table cell. I think the choices could be either:
- truncate and provide a way to see the full text
- wrap
- let the table grow horizontally, perhaps requiring a horizontal scrollbar.

I'm inclined towards truncation when there are more than a couple of columns.
I'm inclined towards wrapping when there are just a couple of columns and the typical case would just wrap a couple of lines.
I'm inclined towards horizontal scrolling when the content in that cell is frequently used as a reference when scanning the table looking for a particular row, such as a long primary identifier.

**Comment by vavalos5** [comment]
Some questions from the Figma file:

1. Would truncation be dependent on the amount of text teams want to show? Do/Should we determine after how many characters truncation would happen?

2. Would we want the tooltip to be shown right over the truncated text? Would the placement depend on location?

3. How would a tooltip actually work? Tooltips should only be used on interactive elements and should only contain non-essential content

4. If the text is truncated by means of CSS's text-overflow: ellipsis: , the title attribute is a working solution for screen readers.
It is still being read by screen readers, since the original (visually truncated) text will be fully read. On the other hand, title attributes are not accessible by keyboard, touch screen and other means. We can provide a keyboard and screen reader accessible tooltip that expands the text in a layover. However, if the cell has no interactivity, how would a tooltip actually work? 

5. Should we have t-shirt sizing for density? (See wrapping example in [Figma](https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=1473%3A0) file)

6. Do we want to offer wrapping? Most of the research i’ve done has talked about truncating rather than wrapping as content tends to get too busy. Instead, adjust column width and use horizontal scrolling.

**Comment by ericsoderberghp** [comment]
> 1. Would truncation be dependent on the amount of text teams want to show? Do/Should we determine after how many characters truncation would happen?

I think in general we should let the available real-estate drive it. CSS will automatically truncate at an appropriate character position.

> 2. Would we want the tooltip to be shown right over the truncated text? Would the placement depend on location?

The browser default behavior will take care of this. If we provide our own, and if we use Drop, Drop is intelligent enough to move itself to avoid bumping into the window edges.

> 3. If the text is truncated by means of CSS's text-overflow: ellipsis: , the title attribute is a working solution for screen readers.It is still being read by screen readers, since the original (visually truncated) text will be fully read. On the other hand, title attributes are not accessible by keyboard, touch screen and other means. We can provide a keyboard and screen reader accessible tooltip that expands the text in a layover. However, if the cell has no interactivity, how would a tooltip actually work?

good question, anything in the research around this? If the row has interactivity that shows more details, that would address it.

> 4. Should we have t-shirt sizing for density? (See wrapping example in [Figma](https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=1473%3A0) file)

I didn't see where this was in the Figma file. Are you thinking density of the table content, font size, padding, etc? If so, I'm more inclined to consider density of the overall app than just the table.

> 5. Do we want to offer wrapping? Most of the research i’ve done has talked about truncating rather than wrapping as content tends to get too busy. Instead, adjust column width and use horizontal scrolling.

I think wrapping should be discouraged but perhaps not prohibited entirely, just in case there's a scenario like consistent two-word content that lends itself fairly well to wrapping.

**Comment by vavalos5** [comment]
@ericsoderberghp i was thinking the density would be the padding of the rows. 

So in this example, the first row has some wrapping happening. Since the string of text is stacking, I assume the cell height is automatically adjusted to what's in the theme. I was just wondering whether we'd have an option to have all of the cells change in density so they all look visually the same in spacing or whether the rows with wrapping would just grow larger. I was thinking out loud at that moment.

I'm not sure if there is really a need but I had seen it in other tables such as [Carbon](https://www.carbondesignsystem.com/components/data-table/usage/#sizing) and was curious.

<img width="688" alt="Screen Shot 2020-09-16 at 10 52 56 AM" src="https://user-images.githubusercontent.com/62117454/93373887-d2e7f600-f80a-11ea-9f71-9b4bde4a0950.png">
