### ISSUE TITLE
Table header variations for data content

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#1101]
We are showing abbreviated value labels (TiB, B, GiB) in the cell content, however, it would be worth considering placing those value labels in the header:

Capacity (TiB) | Size (GiB) | Pinnable Cache (B)

**Comment by rajasekar-ramasamy** [comment]
Data tables, should unit type be in the column header, or with the column data?
I  have created 2 option considering users' expertise

Option 1: 
Recommended for frequent (expert) users, they will find having the units in the cell unuseful as they are well aware of the units and find them just to be noise

Option 2: 
Recommended for novice users, they will find having the units in the cell-helpful because they don't need to refer to the column heading for understanding. 

Figma Link: 
https://www.figma.com/file/XEoIWIlLfcARRIFhkpFCch/HPE-Table-Component?node-id=1519%3A8
