### ISSUE TITLE
Export Images/Icons 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#121]

**Comment by ShimiSun** [comment]
All the icons translated from SVG to React & Grommet components so we can leverage the theme behavior on the SVGs and the `color` and `size` props.
I'm keeping this issue open since we still need the icons for pages that are not Foundation.
* Guidelines
e.g. Guidelines https://hpe.invisionapp.com/share/NKV7IJ4BTMU#/screens/398011581
* Develop
* Design
* Components
* Resources

**Comment by MikeWalrath** [comment]
@ShimiSun is this still relevant?

**Comment by ShimiSun** [comment]
I think we can close for now and might need to reopen in a more concise way in the future.
