### ISSUE TITLE
Home page tiles should be anchors

### ISSUE THREAD

**Issue by karatechops** [hpe-design/design-system#256]
Href attributes should only live in `a` tags. I believe this is also breaking the keyboard navigation tab flow. I will open a separate issue for this.

![Screen Shot 2020-01-17 at 5 30 11 PM](https://user-images.githubusercontent.com/5983843/72650659-1ffb8b80-394f-11ea-9589-8189b593c3d2.png)

![Screen Shot 2020-01-17 at 5 32 11 PM](https://user-images.githubusercontent.com/5983843/72650737-53d6b100-394f-11ea-9081-124aff847466.png)

**Comment by taysea** [comment]
I think these aren't explicitly anchors or buttons because it is using the onClick prop that was recently added to grommet Box. However, this is a good point about where hrefs should appear and we should check on that. For context, the href that is appearing is being passed down from Nextjs Link that's wrapping each of these tiles.

The tabbing issues aren't because of the fact that it's a div though, because grommet handles keyboard for boxes with 'onClick' props, but is coming from a different issue with how Drop changes tabindex of other elements (link to a PR is on the other issue you opened about this).
