### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by karatechops** [hpe-design/design-system#267]
To be discussed as a team. Items to include:
- User acceptance criteria

**Comment by MikeWalrath** [comment]
@taysea is this posted somewhere to take a look at?

**Comment by taysea** [comment]
@MikeWalrath Here is the WIP (adapted from grommet) please drop feedback:


### Is this issue related to the design system core library or design system website?

### Expected Behavior

### Actual Behavior

### URL, screen shot, or CodeSandbox exhibiting the issue

### Steps to Reproduce
1. 2. 3.
### Your Environment

- Design System version:
- Grommet version:
- Browser Name and version:
- Operating System and version (desktop or mobile):

**Comment by ShimiSun** [comment]
LGTM
