### ISSUE TITLE
Update patterns to not use internal components 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#649]
We would like to update the pattern example code to work as easily as possible. To copy/paste the code and have it work.

**Comment by britt6612** [comment]
Some of the code that is used in our Patterns is from `aries-core` since we have not published those.  we should get clarification here on approach for if this would be okay to show these or not. 

Also `ScreenContainer` code is used but it is more of a template for us to showcase what things look like in full screen and mobile screen. If someone were to copy and paste they would not fully understand the context behind this code. We can maybe wrap this within our example page and use as a prop that way its still getting wrapped in the `ScreenContainer` but this would not be needed.
