### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#703]
Acceptance criteria is based on alignment across the below 
- [x] Figma 
- [x] Theme
- [x] Grommet
- [x] Code Examples
- [ ] Guidance

**Comment by vavalos5** [comment]
I'm placing this for now. I'm still going to add/edit this, but leaving what I've been working on here.

### **Guidance**
The footer is always used at the bottom of each application and webpage to navigate an array of company information and other important links to essential pages.

### **Usage**
A footer is a consistent element to be used at the bottom of all of your applications or webpages.

**Always provide these essential links on your footer:**

**Copyrights Information**
It is vital to make it clear that the content within the website and applications are protected and copyrighted.

**Terms of Use**

**Privacy**

As a large corporation, it is essential to display a link to our privacy policy page to let users know that we follow GDPR laws.

**Security**

**Feedback**

### **App Footer**

A simple, clean and straightforward app footer can quickly display useful information for the user that couldn’t be displayed on the header.

### **Page Footer**

A simple, clean and straightforward app footer can quickly display useful information for the user that couldn’t be displayed on the header.

It is always below the body that includes additional information the user didn’t find in the main body.

**Comment by vavalos5** [comment]
Second pass. Feel free to change anything on here or if you have suggestions:

### **Guidance** 

A Footer is used to navigate an array of company-wide information and other important links to essential pages for consistent user experience through out webpages and applications.


### **About Footer:**

The footer is a consistent element at the bottom of all of your applications or webpages.

**Common use cases include:**

- A way to provide additional options that were not on the Header 
- Providing an intentional scroll for users to find important information they would expect 

**Components used within Footer:**

- The only component used on the Footer is Button. 


### **Usage**

Unlike the Header, the Footer is not a flexible composition and should remain exactly as the examples provided.

**Always provide these essential links on your footer:**

**1. Copyrights Information** 
It is vital to make it clear that the content within the website and applications are protected and copyrighted.

**2. Terms of Use**
These guidelines will help ensure partners and customers the terms of doing business with us.	

**3. Privacy**
As a large corporation, it is essential to display a link to our privacy policy page to let users know that we follow GDPR laws.	

**4. Security**
It is important for users to get an overview that explains our security processes and tools that are used to protect data and users.

**5. Feedback**
It is very important to get feedback from users as often as possible.


### **App Footer**

A simple, clean and straightforward app footer can quickly display useful information for the user that couldn’t be displayed on the header.

**An App Footer should:**

- Always have application navigation structure
- Always be below the body
- Contain actions relevant to a single page of an app



Page Footer

A simple, clean and straightforward app footer can quickly display useful information for the user that couldn’t be displayed on the header.

A page footer should:

Always be below the body 
Contain actions relevant to a single page of an app
-  Always be used in addition to the App Header

Accessibility

When using Footer, use Buttons as your your navigational element to activate a section. For guidance, tab through the Footer with navigational buttons. <— (this should direct them back to the Footer example)
