### ISSUE TITLE
Border/edge sizing and gap/margin/padding audit

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#746]

**Comment by vavalos5** [comment]
#771

**Comment by vavalos5** [comment]
#770

**Comment by vavalos5** [comment]
#771

**Comment by halocline** [comment]
[Audit Summary](https://docs.google.com/document/d/1P7mubJ54SpK8cadf7jL4OKW2GlnHs9XIwL1hVBew-Mw/edit?usp=sharing)

After auditing, I am seeing minimal instances where spacing has discrepancies between design & theme:
- Anywhere where Default Button is being consumed by another component (e.g. Menu, Accordion, Select - related issues: https://github.com/grommet/grommet/issues/4077, https://github.com/hpe-design/design-system/issues/770, https://github.com/hpe-design/design-system/issues/771)
- `global.drop.extend.margin-top` is 3px in theme, should be 4px
- Spacing between FormField input and surrounding text (e.g. label, help, info, error -- related issue / work-in-progress: https://github.com/grommet/grommet-theme-hpe/pull/69/files#diff-99a85c3932c0670278158f38d818e0ef)

With completion of the three bullet points above, we should have the spacing in alignment.

That said, I think there should be a Dev discussion around directly specifying pixel values in the theme vs. using variable namespaces for a spacing. There are actually very few instances of directly specifying values outside of button definitions.

**Comment by ericsoderberghp** [comment]
Glad to hear we don't anticipate changing the t-shirt sizes.

I think we should be using t-shirt size labels rather than numeric pixel values in the theme.

What's driving the drop margin-top to not be a t-shirt size?

**Comment by halocline** [comment]
> I think we should be using t-shirt size labels rather than numeric pixel values in the theme.

That would be my preference as well. That said, we currently are leaning on values of 2px and 4px [defining the new button sizes](https://github.com/grommet/grommet-theme-hpe/blob/976950bdc7d634152822761fdd1d0061a58af993/src/js/index.js#L256), for [border-radii](https://github.com/grommet/grommet-theme-hpe/blob/976950bdc7d634152822761fdd1d0061a58af993/src/js/index.js#L501), and margin/padding in a few instances which aren't represented as t-shirt sizes.

> Glad to hear we don't anticipate changing the t-shirt sizes.

The main crux is how we want to use 2px and 4px, but the current t-shirts for edgeSize descend from 24(md)-12(sm)-6(xs)-3(xxs)-1(hair)-0 where 2 and 4 are not represented.

So the options I see are:
- Create a namespace for the values of 2px and 4px to live under in addition to the current t-shirt sizes
- Break the "half-life" of t-shirt sizes at `xxsmall` and let that point to a value of 4px instead of the current 3px (There are a few instances where `base.js` is currently breaking this for [borderSize](https://github.com/grommet/grommet/blob/d32225ac1a7d02a0beba63aae6fa13fa3bc6e85d/src/js/themes/base.js#L159) and [edgeSizes at small breakpoint](https://github.com/grommet/grommet/blob/d32225ac1a7d02a0beba63aae6fa13fa3bc6e85d/src/js/themes/base.js#L176)).
- Modify designs to use the 3px and 6px instead of 2px and 4px.
- Be okay with circumstances mentioned above being specified values rather than variable references.

 
> What's driving the drop margin-top to not be a t-shirt size?

It is currently set at an edgeSize of `xxsmall` whose value is 3px, which doesn't align to the desired 4px.


Here is a [comprehensive summary](https://docs.google.com/document/d/1P7mubJ54SpK8cadf7jL4OKW2GlnHs9XIwL1hVBew-Mw/edit?usp=sharing) of the audit. I can set up a call if best to talk through the findings and options.

**Comment by gregfuruiye** [comment]
I adjusted our label and description margin to 6px. In the image below, the left is 4px and the right is 6px. As you can see, there's very little change here, so the direction is to just get aligned
<img width="618" alt="Screen Shot 2020-05-27 at 10 31 05 AM" src="https://user-images.githubusercontent.com/17889451/83047134-31dbf200-a005-11ea-82da-ac19fb098cf4.png">

**Comment by ericsoderberghp** [comment]
Firstly, thanks for the detailed audit and identification of options, well done.

My current thoughts ...

How can we get `theme.global.borderSize` t-shirt sizings to work better with `theme.global.edgeSize` t-shirt sizings? For instance, if I have a Box with pad=medium and no border, I should be able to adjust pad and border to maintain the same overall Box dimensions. This is what the HPE Button theme is trying to accomplish.
- One approach would be to adjust the border sizes to align with the edge sizes. But, this makes the border sizes a bit unwieldy as typical border sizes are less than typical pad and margin sizes.
- Another approach would be to make it easier to define combined sizing math. For instance, pad="medium - border:small". This feels a bit complicated.
- Another approach would be to specify whether the pad should automatically be adjusted to adapt to the border size. For example: `pad={{ size: 'medium', includeBorder: true }}` or maybe something like `pad="medium"` and `padIncludesBorder={true}`. This would work both for Button but also for other scenarios, for instance when a border is tied to hover indication.I'm leaning towards this option.

**Comment by ericsoderberghp** [comment]
I think adjusting the Figma side for FormField to align with the grommet edge sizes sounds like the right approach.

I'm OK with the drop margin-top using a custom pixel value, as I don't see that having the same sort of alignment issues as other places where pad and margin are used.

**Comment by ericsoderberghp** [comment]
I'm fine with the text component theming for Heading, Paragraph, and Text being tied more towards relative font sizing and less tied directly to the layout t-shirt sizes.

**Comment by ericsoderberghp** [comment]
I'm inclined to see if we can use a t-shirt sized border radius in Figma instead of a custom one, as that will make it easier to have other elements having the same radius, and therefore more aligned.

I don't think we should create custom sizing labels within the HPE theme for mapping 2px and 4px values. I think we should stick with the current t-shirt sizing labels.

**Comment by gregfuruiye** [comment]
Chris and I touched on this just a bit when I was working on box. As the box size grows, and subsequent padding, then should border scale as well. We both suggested that this is not likely the case, so not sure I'm keen on having a relationship with border and edge size. For example, I may have cards with 1px border, but with one box 96 x 192 and another at 192 x 384 where padding is 12 on the small box and 24 on the larger box, but still have 1px border for both.

I know we have some issues related to 3px border sizes and radius that is creating some 'fuzzy' spaces. It is a bit odd in Figma when half pixel issues crop up using 3px for border and radius. There's more to that story I'm sure.

We will adjust the FormField sizes on Figma to 1, 3, 6... sizing

I thought I saw 'round' for box with t-shirt sizing at 1, 3, 6... If so, I wonder if we also adjust designs back to these.

If we went to new t-shirt sizing and shifted a bit of everything to 4px based spacing, then the maths get interesting based on our basespacing, correct? But if we 'fudged' on the 3px and made it four (0, 1, 2, 4, 6, 12, 24, 48...), where would that take us? It makes the curve a bit funky, but is that really the right thing to do?

**Comment by halocline** [comment]
Documenting decisions made:
- For margin, pad, gap - align Figma to edgeSize - t-shirt sizing --> 24, 12, 6, 3, 1, 0
- For border width, border radius - align theme to Figma
- Get discussion in Grommet queue on how to handle border/pad calculations automatically

**Comment by MikeWalrath** [comment]
@halocline I got it
