### ISSUE TITLE
Select component on Design System site card has wrong text height

### ISSUE THREAD

**Issue by vavalos5** [hpe-design/design-system#768]
### Is this issue related to the design system core library or design system website? 

Design System website

### Expected Behavior

Text height is 36px but should be 24px. Once corrected, keep left and right padding of 12px and 6px on top and bottom.

### Actual Behavior

Text height is 36px with left and right padding of 12px and 6px on top and bottom.

### URL, screen shot, or CodeSandbox exhibiting the issue
<img width="1201" alt="Screen Shot 2020-05-11 at 11 56 03 AM" src="https://user-images.githubusercontent.com/62117454/81606055-3eb2e180-9387-11ea-9b75-6087f247d04b.png">

Please refer to Figma file:  https://www.figma.com/file/fZJdRcNrvZ1JjdPRYHpFFU/HPE-Select-Component?node-id=103%3A140

**Comment by halocline** [comment]
PR - https://github.com/grommet/grommet-theme-hpe/pull/68

**Comment by halocline** [comment]
@vavalos5 - The fix is live on the site. Can you please confirm it is displaying as expected?
![Screen Shot 2020-05-12 at 9 31 32 AM](https://user-images.githubusercontent.com/1756948/81713659-62cbfc80-9433-11ea-9066-2c2768718dde.png)

![Screen Shot 2020-05-12 at 9 30 41 AM](https://user-images.githubusercontent.com/1756948/81713609-534cb380-9433-11ea-8958-731755afcce8.png)
![Screen Shot 2020-05-12 at 9 30 47 AM](https://user-images.githubusercontent.com/1756948/81713621-55af0d80-9433-11ea-9a0c-75d6ce6bbe27.png)

**Comment by vavalos5** [comment]
@halocline Looks good! Thanks for fixing :)
