### ISSUE TITLE
Update landing page text

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/design-system#857]
https://publisher.grommet.io/recommendations?id=2020-Q2-HPE-Design-System-Study-greg-furuiye-hpe-com

Title and subtext is clear and concise on the home page, without losing its playfulness
- Some participants were misled with the 'game'
- Most participants were unsure of 'carte' in this context, "Is this a codename?"

### Deliverables
- [ ] updated descriptive text on the design system site

expected to take < 1 day.

**Comment by cherih** [comment]
Got this new issue. Thanks!

Cheri

**Comment by cherih** [comment]
Proposed new title and sub-title for the DS landing page.. Looking for comments this afternoon, so that changes can be made to the DS website tomorrow.


### HPE Design System

The Design System was created to empower designers, developers, and others to contribute to making great experiences for the customer.

**Comment by cherih** [comment]
Thanks to Taylor for updating the DS website with this copy!

I verified that the updates look as expected.
