### ISSUE TITLE
Create video content proof of concept

### ISSUE THREAD

**Issue by halocline** [hpe-design/design-system#888]

**Comment by gregfuruiye** [comment]
I'm going to work on some of the content for the guidance and review it with the designers so that it aligns with some of the content in the video a bit more. I'll work on that, and post it here early next week.

I think my first impression thoughts are:
- The start size of the video is too big. I rendered it in a larger size for full viewing, but maybe we can start at 360 (or even 240) rather than 720 and allow full size from there?
- The video starts with a blank screen intentionally, but I think I should have a single frame of content so that when the video is sitting there prior to pushing 'play' there is a sense that content is actually there.
- We will likely have 3-4 Figma videos. Should all of them be together at the bottom of the content? Just thinking out loud here. Or, keep the videos associated with the section and get them smaller to start off? I'm thinking smaller and associated with the text content.

**Comment by halocline** [comment]
> * The start size of the video is too big. I rendered it in a larger size for full viewing, but maybe we can start at 360 (or even 240) rather than 720 and allow full size from there?

👍

**Comment by halocline** [comment]
> * The video starts with a blank screen intentionally, but I think I should have a single frame of content so that when the video is sitting there prior to pushing 'play' there is a sense that content is actually there.

👍

**Comment by halocline** [comment]
> * We will likely have 3-4 Figma videos. Should all of them be together at the bottom of the content? Just thinking out loud here. Or, keep the videos associated with the section and get them smaller to start off? I'm thinking smaller and associated with the text content.

Keep associated with context.

**Comment by halocline** [comment]
> * I always struggle with volume and finding the volume controls here are kind of hidden. Can we pull that control out into the control bar instead of in the settings?

Doable, yes. I haven't gotten to play with Video component much so I'd need to research what would be involved.
