### ISSUE TITLE
Add guidance to Page Layouts

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#917]
Build off of https://github.com/hpe-design/design-system/issues/887 and https://github.com/hpe-design/design-system/pull/908 by adding guidance copy explaining when to use each layout as well as anything distinctive about the layout, such as responsive and scroll behavior notes, typical templates and components used to fill out the layouts, etc.

### Deliverables

- [ ] guidance text written in a pull request
- [ ] guidance text reviewed, either via GitHub, Slack, or a meeting
- [ ] guidance text published

expected to take 2-3 days

**Comment by cherih** [comment]
@team - the initial pass of the Page Layouts page has some guidance built into each Page Layout example. I'm assuming that for this issue that I'm working on, you're looking for additional guidance for when to use the different layouts. Is this what you're thinking?

I browsed several related issues (797, 887, 907 and 908). Tomorrow, I'll also look at 918 and 919. Are there any others that I should look at as well for this issue?

**Comment by taysea** [comment]
#919 and the PR that closes it would definitely be good. We don't have any copy on the site about that right now, but we will want to talk about how the page content can expand to a max-width and after that it stays centered. That behavior is demonstrated visually when a user clicks on "Desktop" but having written guidance would be helpful.

**Comment by cherih** [comment]
@taysea - Thanks for the pointer to these additional issues!

**Comment by vavalos5** [comment]
I've added a few bullet points that I thought could be helpful for you.

- Page layouts are to be used before beginning any designs for your application. 

- How to support different resolutions.

- it is important to follow one of these layouts provided so that your app can be available to the greatest numbers of users.

- These page layouts show how to build and support different screen sizes.

- When a browser is larger than 1440px, constrain the sidebar, main, footer, header, and grid to stay centered with equal margins on both sides.

** Also would be good to direct some of the context to other links within the design system such as: header, main, footer, sidebar and grid

**Comment by cherih** [comment]
@vavalos5 - Thank you for these bullet points! I'll incorporate the info into the guidance I'm working on.

**Comment by cherih** [comment]
Initial pass of content for review:

### Guidance
The when, how, and why to use page layouts.

**About Page Layouts**
Choosing a page layout is an important first step in designing an application or website. Use of these layouts will help to maintain consistency across your design. They also provide visual guidance for how your design behaves at different screen sizes.

**Common use cases include:**
•	Creating a dashboard with global navigation
•	Providing a dialog for viewing or updating something
•	Displaying a page in a website

**Components used within a Page Layout:**
Page Layouts are built using the Header and Main components, with optional Sidebar and Footer components. For guidance on page layout content, refer to the HPE Design System website pages for the components that make up your Page Layout.

**Usage**
Page Layouts provide the basic structure for a variety of page types. 
•	Page-level vertical scrolling is supported, but horizontal scrolling is not (and should be avoided, when possible).
•	Can be used with various Navigation patterns. 
•	Are designed to be responsive, and thus behave well, regardless of the screen size they are displayed on.

**Responsiveness**
Examples are included for different screen sizes – Desktop, Laptop and Mobile. 

Page content can expand to a max-width of 1440px and after that it stays centered. Specifically, the sidebar, main, footer, and header are constrained to stay centered, with equal margins on both sides. This behavior is demonstrated visually when a user clicks on a Desktop example.

**Accessibility**
The screen reader reads page content in the order it is specified. Refer to the code examples to see the order in which Page Layout components are specified. Since Sidebar is typically used for global navigation, it is always specified first in Page Layout, when it is included. 

Specify page layout content so that it is understandable by the screen reader too. This should make the page easier to visually read as well.

### Variants
Examples of common page layouts.
