### ISSUE TITLE
Tab disabled state updated in Theme

### ISSUE THREAD

**Issue by gregfuruiye** [hpe-design/design-system#920]
The disabled tab state is not appearing on the site or in the designer:

https://design-system.hpe.design/components/tabs#tab-states

**Comment by gregfuruiye** [comment]
The intended state is defined in Figma using text-weak and border-weak for color.

https://www.figma.com/file/Kp4dWyhUTnKIJ1Cg5CoL9o/HPE-Tabs-Component?node-id=208%3A0

**Comment by halocline** [comment]
The loss of the disabled styling appears to be a side effect of the recent Button work. In the DOM, the disabled button's class is the same as its peers'.  When `button.default` is removed from theme, the disabled styling resembles previous behaviors.

Looking into Grommet implementation for Tab and/or Button to isolate issue.

**Comment by halocline** [comment]
**Update**
Findings: 
- Tab uses `<Button plain />` for functionality and then styles the inner child independently
- Prior to the implementation of ButtonKind, `<Button plain />` received styling from StyledButton which receives disabled state styling from `/utils/styles` --> `disabledStyle()` which set the `opacity` and `cursor`
- StyledButtonKind is looping through the 'kinds' and getting all styling from the theme.button object, but is not incorporating the `disabledStyle()` from `utils` --> NOTICE: the cursor when hovering over the disabled button is a pointer rather than default: https://design-system.hpe.design/components/button#button-states
- Since HPE Theme is using ButtonKind, `<Button plain />` is no longer receiving the opacity and cursor styling it had previously
- Additionally, Tab does not currently have disabled styling, nor is the disabled prop being passed to the inner child

Recommendation:
- Update `StyledButtonKind` to incorporate `disabledStyle()` from utils (cursor flows through, button.opacity gets overwritten by HPE Theme)
- Pass `disabled` prop to `StyledTab` --> update StyledTab to reference `theme.tab.disabled` add to theme object

**Comment by taysea** [comment]
Thanks for the really clear summary. Super helpful to see it documented like this. To me, carrying over the `disabledStyle()` work makes sense, but can you clarify why a new theme object needs to be added?

**Comment by halocline** [comment]
The way I am thinking about it is:
- Since Tab is implemented with `<Button plain />` it is no longer receiving any styling from Button's definitions --> therefore, styling should come from Tab/StyledTab.
- Tab receives styling for text-color, border, pad, margin, plus `active` and `hover` states. `disabled` is yet another state, so I was thinking it should follow the established pattern and include it with `active` and `hover`.

Alternate ideas?

**Comment by taysea** [comment]
Gotcha, I guess where I got confused is when you said:

> Prior to the implementation of ButtonKind, <Button plain /> received styling from StyledButton which receives disabled state styling from /utils/styles --> disabledStyle() which set the opacity and cursor

Prior to the StyledButtonKind changes, Tabs had the proper disabled styling and in the current moment the grommet tabs still have proper disabled styling without an added theme object (even though it's still using plain, right?). So to me, we should be able to achieve the disabled styling the same way grommet theme tabs are.

However, it does makes sense to me to add the theme object for consistency of states. It just seems suspicious that it would need to be added to fix this bug.

**Comment by halocline** [comment]
It would achieve it if we hadn't also added `button.opacity: '1.0'` to the theme, which overrides the `opacity: 0.3` coming from `utils/styles/disabledStyle()` which Grommet has.

Additionally, as I have been working through this, if I specify `plain` my expectation is that no styling will come through; I wouldn't want some phantom styling leaking through and not giving me plain.

**Comment by halocline** [comment]
Filed the following to fix:
https://github.com/grommet/grommet/pull/4232
https://github.com/grommet/grommet/pull/4233

**Comment by halocline** [comment]
This can be closed once: https://github.com/grommet/grommet-theme-hpe/pull/83 is merged.
