### ISSUE TITLE
Add List guidance

### ISSUE THREAD

**Issue by taysea** [hpe-design/design-system#964]
Pulling from comments on https://github.com/hpe-design/design-system/pull/956

- [ ] In each variant, elaborate on each unique element (image, icon, status, etc.). For example, we should explain how image should be used to assist scan-ability -- specific to this example, the image should be tied to the data present.
- [ ] What happens with longer labels? (at various widths), does text truncate, wrap?
- [ ] What happens with subtitle/descriptions? (at various widths), does text truncate, wrap?
- [ ] Max-width of lists used to ensure readability/scan-ability. `xxlarge` is max-width for page content, so should list follow this?
- [ ] Accessibility: List `action` button and `onClick` should not be used together. Either the entire list item has an `onClick` or there is an action button on the far right of the list item.
- [ ] What is the anatomy of a list item?
- [ ] When do I use List vs Table?
- [ ] Hover state: If the entire list item is clickable, the background of a list item receives the active background color and the cursor changes to a pointer hand. Otherwise, there is no hover state when a list item is not interactive. If a list item contains an action button, then that button respects its natural hover behavior.

Also, we could likely improve the mock data to feel more realistic. If @cherih or others have thoughts on what the data should be, feel free to comment that here.

**Comment by cherih** [comment]
Recommend wrapping for longer labels and subtitle/descriptions. 

We have customers who use long names (>100 chars) and they really need to distinguish one from the other. Truncating often ends up with multiple list entries that look the same, but really aren't.

**Comment by cherih** [comment]
Comments/questions about Lists from Matt Borland's "State of the HPE Design System" document (July 2020):

https://design-system.hpe.design/templates/lists

Lists are very critical elements to an application. How they are implemented guides a large part of the user experience. This area provides no direction regarding lists. I would expect guidance like:

o	How does it fill the page / area (both horizontally and vertically)? e.g. Scrollbars?
o	What are the behaviors of the list (hover states)?
o	How does the list handle pagination or infinite scrolling?
o	How does the list allow for searching or filtering?
o	Does the header to the list remain static if scrolling (so actions like Manage below are always present)?
o	Are there guidelines for icon use, sizing, text use and sizing, status, and actions?

**Comment by cherih** [comment]
I'm thinking for this initial pass of the Lists, we will be able to address some of the comments from Matt B above, but not all of them. We'll need to have conversations with the GLC UX/DS teams to discuss Lists further and decide how to iterate on the Lists page.

**Comment by cherih** [comment]
### Guidance
The when, how, and why to use lists.

**About Lists**
HPE Design System list view templates are go-to patterns for deploying homogeneous data such as services, devices, users, and more. List views are optimized for scanability and reading comprehension. Each list item provides users focused information and identity labels to aid selection, decision making, and action.

Lists are an effective way to display dense content to users. Here are some recommendations on how to make the data easily consumable.

**Best Practices:**
•	Be consistent with layout and visual treatments for all list items.
•	Keep list item descriptions brief and concise.
•	Use icons or images in list items to help draw attention and support scanning.
•	Maintain sufficient space between list items or consider using dividers between rows.
•	Sort lists in a logical order such as alphabetically, numerically, chronologically, or by user preference.

**Usage**
The following list types are supported:
•	Single-line lists are optimal for scan-ability, especially with the addition of an image.
•	Two-line lists provide a primary and secondary text which can be helpful when more detail is needed.
•	Three-line lists of a primary text and two lines of secondary text are not recommended.
•	Grid lists are made of image files and require more space.

**Selection**
Use either selection of a whole list item or clickable areas on a list item (such as the action menu button). Do not combine these. 

Use hover states to indicate which kind of selection is being used.  If the entire list item is clickable, the background of the list item receives the active background color and the cursor changes to a pointer hand. Otherwise, there is no hover state for a list item that is not interactive. If a list item contains an action button (or other clickable area), then that button respects its natural hover behavior.

Selection use cases include:
•	A list with selectable items and a single action menu on the same page, allows for multi-selection of items
•	A list with selectable items and no action menu on the same page, allows an item to be selected. When an item is selected, a detail view can be shown with a single action menu for performing other things, such as powering on or off a device. Multi-select is not supported.
•	A list without selectable items, but an action menu on each item, allows an action to be performed inline on a single item. Multi-select is not supported.

**Long Lists**
•	Add a sticky header for the list
•	Avoid using multiple vertical scrollbars
•	For really long lists (i.e. hundreds or thousands), consider limiting the number of items that can be shown at a time and provide some mechanism for accessing the rest of the items
•	Provide search and filtering capabilities to allow customers to quickly find specific list items
•	Avoid paging, if possible. It is difficult to do and can result in a confusing user experience

**Responsiveness**
Examples are included for different screen sizes – Desktop, Laptop and Mobile. 

Lists should span the width of the page it is in, unless it is placed in a constraining box.

Long data in lists should be wrapped, rather than truncated. We have customers who use long names (>100 chars) and they really need to distinguish one from the other. Truncating often ends up with multiple list entries that look the same, but really aren't.

**Accessibility**
Lists are usually easier to navigate than tables. When creating a design that uses a table, especially a simple table, consider whether a list could be used instead.

### Variants
Examples of common lists.

**Comment by taysea** [comment]
I've added this first pass to the first pass of the list page. We can continue to add and make iterations though.

**Comment by cherih** [comment]
@taysea - thanks for adding the first pass of list guidance to the first pass of the list page.

**Comment by cherih** [comment]
Here are some thoughts on the questions Taylor raised in the e-mail yesterday:

**List vs Table**
-	If space is limited, a List uses less room than a Table
-	Use a List, If scanability is desired. It’s easier to read than a Table
-	If items can be selected using only the List contents, then use a List

**Action Menu in List Item**
-	If space is limited, then don’t use an Action Menu in a List item (repetition of the Action Menu icon uses a lot of space)
-	If items can be selected using only the List contents, then use an Action Menu in a List item. Otherwise, go to a detail view to see additional information for the List item and use an Action Menu there.
-	If an action is simple and the results can be seen in the List contents (e.g. enable/disable), then use an Action Menu in a List item
-	If multi-select is required, then don’t use the Action Menu in the List item.

**Truncation vs Wrapping**
-	The recommendation is to always wrap data, rather than truncate. Or always wrap?
-	A useful article related to this:
o	https://medium.com/we-build-vend/why-you-should-never-truncate-in-ui-2823cca61d5a
-	It’s about respecting the user’s content, that is, the words they type in.
-	If for some reason the “Do not truncate” rule must be broken, then some way must be provided to see the entire content.

**Comment by cherih** [comment]
Here is an updated pass of the List Guidance. It includes new sections for:
- Lists vs Tables
- Action Menu in List Item

Also, updated the wrapping vs truncation in the Responsiveness section.

***

### Guidance
The when, how, and why to use lists.

**About Lists**
HPE Design System list view templates are go-to patterns for deploying homogeneous data such as services, devices, users, and more. List views are optimized for scanability and reading comprehension. Each list item provides users focused information and identity labels to aid selection, decision making, and action.

Lists are an effective way to display dense content to users. Here are some recommendations on how to make the data easily consumable.

**Best Practices:**
•	Be consistent with layout and visual treatments for all list items.
•	Keep list item descriptions brief and concise.
•	Use icons or images in list items to help draw attention and support scanning.
•	Maintain sufficient space between list items or consider using dividers between rows.
•	Sort lists in a logical order such as alphabetically, numerically, chronologically, or by user preference.

**Usage**
The following list types are supported:
•	Single-line lists are optimal for scan-ability, especially with the addition of an image.
•	Two-line lists provide a primary and secondary text which can be helpful when more detail is needed.
•	Three-line lists of a primary text and two lines of secondary text are not recommended.
•	Grid lists are made of image files and require more space.

**List vs Table**
A List or a Table can be used to represent a set of related items, such as servers or devices or users. The one that is chosen will depend on the specific use cases that need to be supported.
•	If space is limited, a List uses less room than a Table
•	Use a List, If scanability is desired. It’s easier to read than a Table
•	If items can be selected using only the List contents, then use a List

**Selection**
Use either selection of a whole list item or clickable areas on a list item (such as the action menu button). Do not combine these. 
Use hover states to indicate which kind of selection is being used.  If the entire list item is clickable, the background of the list item receives the active background color and the cursor changes to a pointer hand. Otherwise, there is no hover state for a list item that is not interactive. If a list item contains an action button (or other clickable area), then that button respects its natural hover behavior.

Selection use cases include:
•	A list with selectable items and a single action menu on the same page, allows for multi-selection of items
•	A list with selectable items and no action menu on the same page, allows an item to be selected. When an item is selected, a detail view can be shown with a single action menu for performing other things, such as powering on or off a device. Multi-select is not supported.
•	A list without selectable items, but an action menu on each item, allows an action to be performed inline on a single item. Multi-select is not supported.

**Action Menu in List Item**
•	If space is limited, then don’t use an Action Menu in a List item (repetition of the Action Menu icon uses a lot of space)
•	If items can be selected using only the List contents, then use an Action Menu in a List item. Otherwise, go to a detail view to see additional information for the List item and use an Action Menu there.
•	If an action is simple and the results can be seen in the List contents (e.g. enable/disable), then use an Action Menu in a List item
•	If multi-select is required, then don’t use the Action Menu in the List item.

**Long Lists**
•	Add a sticky header for the list
•	Avoid using multiple vertical scrollbars
•	For really long lists (i.e. hundreds or thousands), consider limiting the number of items that can be shown at a time and provide some mechanism for accessing the rest of the items
•	Provide search and filtering capabilities to allow customers to quickly find specific list items
•	Avoid paging, if possible. It is difficult to do and can result in a confusing user experience

**Responsiveness**
Examples are included for different screen sizes – Desktop, Laptop and Mobile. 

Lists should span the width of the page it is in, unless it is placed in a constraining box.

Wrapping vs Truncation:
•	Long data in lists should be wrapped, rather than truncated. 
•	It’s about respecting the user’s content; that is, the words they type in.
•	We have customers who use long names (>100 chars) and they really need to distinguish one from the other. Truncating often ends up with multiple list entries that look the same, but really aren't.
•	It can also apply to automatically generated data, such as product names and descriptions.
•	If for some reason the “Do not truncate” rule must be broken, then a way must be provided to see the entire content.

**Accessibility**
Lists are usually easier to navigate than tables. When creating a design that uses a table, especially a simple table, consider whether a list could be used instead.

### Variants
Examples of common lists.

**Comment by cherih** [comment]
@taysea - thanks for pulling the latest version of the Lists guidance over to the first pass preview!

**Comment by cherih** [comment]
Note - @ericsoderberghp made comments on the combined guidance on the initial pass of list page:
https://github.com/hpe-design/design-system/pull/956

@taysea - rolled in responses to most of Eric's comments and got the OK to push everything to prod.

Still need to look at Eric's Action Menu comments and work with Taylor to update them.

**Comment by cherih** [comment]
Proposed update for Eric's Action Menu comment:

If items can be acted upon using only the List contents, then use an Action Menu in a List item. Otherwise, for more context, go to a detail view for the List item and use an Action Menu there.

**Comment by cherih** [comment]
@taysea - the above comment was the only one I saw that still needed addressing. Was there anything else to fix at this point?

**Comment by taysea** [comment]
@cherih I think that was the only thing that needed to be fixed based on the feedback. In reference to "detail view", I'm wondering if we could be a little more clear on that wording and what it would mean. Does "detail view" mean routing to a new page? Maybe something like:

"If more context is needed to perform an action, the entire list row should be clickable and should route the user to a detail page for the List item. On this detail page, an Action Menu can be provided to engage with the list item data."

**Comment by cherih** [comment]
@taysea - yes, going to the "detail view" means routing to a new page. 

I like what you came up with. Can you please push this last change to the prod version of the Lists page?

Once it's out there, I'll mark this issue as done.

**Comment by cherih** [comment]
@taysea - thank you for pushing the final change for this issue and closing it.

Looks like we're done with this one - hooray!!!
