### ISSUE TITLE
First pass at Wizard template

### ISSUE THREAD

**Issue by ericsoderberghp** [hpe-design/design-system#997]
### Deliverables

- [ ] Wizard page in design system
- [ ] links to Figma
- [ ] initial guidance, more guidance can follow in a separate backlog item later

Build off of https://github.com/hpe-design/design-system/issues/849

I suggest starting with a dev/design review of the figma content. We can create new backlog items for additional design work as needed.

**Comment by MikeWalrath** [comment]
Initial feedback from Edgar. Some of it being opinion based and some of it needing further discussion ex: showing the number of steps. I think number 1 is most relevant at the moment. 

1) What's going on with the scroll region?  The header and next button should be fixed and the content within should scroll (when the screen is smaller).  

2) Seems like the step titles are way too large.  

3) The last button "Finish Setup" is a bit too specific In fact, the setup context is in the descriptive text too.  Wizard doesn't imply setup.  

4) I'm not sure that indicating the step you are on is always going to be a good idea.  The number and organization of steps can easily differ based on the choices the user makes within the wizard.

**Comment by MikeWalrath** [comment]
Some additional thoughts from Edgar. 

More wizard Feedback: when clicking next, there should be a form validation (and we know how that works), but an API may also get called and it may do a deeper business-logic validation that fails.  In Lauren's design, we have a message showing up above the next button for these cases.  We also discussed wizard implementation with the Saturn team today and they were concerned (rightly so) that the final submit may encounter problems (due to race conditions, etc) that invalidate input in earlier steps.  How to deal with that?
